//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public int AccountTransactionID { get; set; }
        public int AccountID { get; set; }
        public int PaymentID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal OldBalance { get; set; }
        public decimal NewBalance { get; set; }
        public bool Usable { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Payments Payments { get; set; }
    }
}
