//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.AccountTransaction = new HashSet<AccountTransaction>();
            this.Links = new HashSet<Links>();
            this.LoginLog = new HashSet<LoginLog>();
            this.MethodCommissionTree = new HashSet<MethodCommissionTree>();
            this.MethodPreference = new HashSet<MethodPreference>();
            this.MoolsEpinPreference = new HashSet<MoolsEpinPreference>();
            this.MoolsEpin = new HashSet<MoolsEpin>();
            this.Payments = new HashSet<Payments>();
            this.Site_ChangePasswordLog = new HashSet<Site_ChangePasswordLog>();
            this.Site_ForgotPasswordLog = new HashSet<Site_ForgotPasswordLog>();
            this.ErrorLog = new HashSet<ErrorLog>();
            this.MoolsEpinGameProducts = new HashSet<MoolsEpinGameProducts>();
        }
    
        public int AccountID { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
        public decimal UsableBalance { get; set; }
        public string DealerCode { get; set; }
        public bool IsActive { get; set; }
        public string Role { get; set; }
        public string NotifyUrl { get; set; }
        public decimal Discount { get; set; }
        public string ReturnUrlSuccess { get; set; }
        public string ReturnUrlFailed { get; set; }
        public string LogoImageUrl_ { get; set; }
        public string PaymentCancelRedirectUrl_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Links> Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MethodCommissionTree> MethodCommissionTree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MethodPreference> MethodPreference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoolsEpinPreference> MoolsEpinPreference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoolsEpin> MoolsEpin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site_ChangePasswordLog> Site_ChangePasswordLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site_ForgotPasswordLog> Site_ForgotPasswordLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoolsEpinGameProducts> MoolsEpinGameProducts { get; set; }
    }
}
