//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string ErrorCode { get; set; }
        public string Message_ { get; set; }
        public System.DateTime LastDate { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Payments Payments { get; set; }
    }
}
