//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoolsLifeEntities : DbContext
    {
        public MoolsLifeEntities()
            : base("name=MoolsLifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<AccountTransaction> AccountTransaction { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
        public virtual DbSet<MethodCommissionTree> MethodCommissionTree { get; set; }
        public virtual DbSet<MethodPreference> MethodPreference { get; set; }
        public virtual DbSet<Methods> Methods { get; set; }
        public virtual DbSet<MoolsEpin> MoolsEpin { get; set; }
        public virtual DbSet<MoolsEpinDealer> MoolsEpinDealer { get; set; }
        public virtual DbSet<MoolsEpinPreference> MoolsEpinPreference { get; set; }
        public virtual DbSet<MoolsEpinUsedLog> MoolsEpinUsedLog { get; set; }
        public virtual DbSet<NotifyLogs> NotifyLogs { get; set; }
        public virtual DbSet<PaymentCurrency> PaymentCurrency { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<Site_ChangePasswordLog> Site_ChangePasswordLog { get; set; }
        public virtual DbSet<Site_ForgotPasswordLog> Site_ForgotPasswordLog { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<MoolsEpinGameProducts> MoolsEpinGameProducts { get; set; }
    }
}
