//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoolsEpinPreference
    {
        public int MoolsEpinPreferenceID { get; set; }
        public int AccountID { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
