//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoolsEpinGameProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoolsEpinGameProducts()
        {
            this.MoolsEpin = new HashSet<MoolsEpin>();
        }
    
        public int MoolsEpinGameProductID { get; set; }
        public int AccountID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal Cost { get; set; }
        public int Currency { get; set; }
        public Nullable<int> ShopierProductID { get; set; }
        public Nullable<int> ShopierHiddenID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoolsEpin> MoolsEpin { get; set; }
        public virtual PaymentCurrency PaymentCurrency { get; set; }
    }
}
