//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoolsEpin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoolsEpin()
        {
            this.MoolsEpinUsedLog = new HashSet<MoolsEpinUsedLog>();
        }
    
        public int MoolsEpinID { get; set; }
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
        public Nullable<int> GameProductID { get; set; }
        public int CreatedAccountID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsBonus { get; set; }
        public Nullable<int> Dealer { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual PaymentCurrency PaymentCurrency { get; set; }
        public virtual MoolsEpinDealer MoolsEpinDealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoolsEpinUsedLog> MoolsEpinUsedLog { get; set; }
        public virtual MoolsEpinGameProducts MoolsEpinGameProducts { get; set; }
    }
}
