//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyLogs
    {
        public int NotifyLogID { get; set; }
        public string From { get; set; }
        public string Content { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime Date { get; set; }
    }
}
