//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolsPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payments()
        {
            this.AccountTransaction = new HashSet<AccountTransaction>();
            this.Links = new HashSet<Links>();
            this.MoolsEpinUsedLog = new HashSet<MoolsEpinUsedLog>();
            this.ErrorLog = new HashSet<ErrorLog>();
        }
    
        public int PaymentID { get; set; }
        public int Type { get; set; }
        public int AccountID { get; set; }
        public int LinkID { get; set; }
        public int MethodID { get; set; }
        public string PayerName { get; set; }
        public decimal Amount { get; set; }
        public decimal Commission { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Message { get; set; }
        public string ApiCode { get; set; }
        public bool IsSend { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public bool IsCancelled { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Links> Links { get; set; }
        public virtual Links Links1 { get; set; }
        public virtual Methods Methods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoolsEpinUsedLog> MoolsEpinUsedLog { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLog { get; set; }
    }
}
